.PHONY: all clean olcPGEX_MiniAudio

all: olcPGEX_MiniAudio

olcPGEX_MiniAudio:
	$(MAKE) -C v1.5
	$(MAKE) -C v1.6
	$(MAKE) -C v1.7

clean:
	$(MAKE) -C v1.5 clean
	$(MAKE) -C v1.6 clean
	$(MAKE) -C v1.7 clean

