[supervisord]
nodaemon=true

[program:app-laravel]
command=php artisan serve --host 0.0.0.0
directory=/home/pgetinker/app
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
priority=100

[program:app-vite]
command=npm run dev --
directory=/home/pgetinker/app
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0

priority=200

[program:language-server]
command=npm run dev
directory=/home/pgetinker/language-server
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
priority=300

[program:screenshot]
command=npm run start
directory=/home/pgetinker/screenshot
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
priority=400

[program:wiki]
command=hugo server -D --baseURL http://localhost/wiki/ --bind 0.0.0.0 --disableFastRender --appendPort=false --logLevel debug
directory=/home/pgetinker/wiki
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
priority=500
