services:
    laravel.test:
        build:
            context: './docker/app'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            APP_URL: '${APP_URL}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        privileged: true
        volumes:
            - '.:/var/www/html'
            - './shared/libs:/opt/libs'
            - './shared/emsdk:/opt/emsdk'
            - '/dev/shm:/dev/shm'
        tty: true        # Allocates a TTY
        stdin_open: true # Keeps stdin open for input
        healthcheck:
            test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:80/api/health-check | grep -q 200"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailpit
            - selenium
            - screenshot
    wiki:
        build:
            context: './docker/wiki'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/wiki'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_URL: '${APP_URL}'
            LARAVEL_SAIL: 1
        privileged: true
        volumes:
            - './services/wiki:/app'
        networks:
            - sail
        depends_on:
            - laravel.test

    language-server:
        build:
            context: './docker/language-server'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/language-server'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_KEY: '${APP_KEY}'
            LARAVEL_SAIL: 1
        privileged: true
        volumes:
            - './services/language-server:/var/www/html'
            - './shared/libs:/opt/libs'
            - './shared/emsdk:/opt/emsdk'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    screenshot:
        build:
            context: './docker/screenshot'
            dockerfile: Dockerfile
        image: 'pgetinker/screenshot'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_ABSOLUTE_URI: ${APP_URL:-http://localhost}/phpmyadmin/
            PMA_ARBITRARY: 1
        networks:
            - sail
    proxy:
        build:
            context: './docker/nginx'
            dockerfile: Dockerfile
        image: nginx
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - sail
        depends_on:
            laravel.test:
                condition: service_healthy
            language-server:
                condition: service_started
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
