services:
    laravel.test:
        build:
            context: './docker/app'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            APP_URL: '${APP_URL}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        privileged: true
        deploy:
            resources:
                limits:
                    memory: 1.5g
        mem_swappiness: 0
        oom_kill_disable: false
        volumes:
            - '.:/var/www/html'
            - './shared/libs:/opt/libs'
            - './shared/emsdk:/opt/emsdk'
            - '/dev/shm:/dev/shm'
        tty: true        # Allocates a TTY
        stdin_open: true # Keeps stdin open for input
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:80/api/health-check"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        networks:
            - sail
        depends_on:
            - redis
            - screenshot
    wiki:
        build:
            context: './docker/wiki'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/wiki'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_URL: '${APP_URL}'
            LARAVEL_SAIL: 1
        privileged: true
        volumes:
            - './services/wiki:/app'
        networks:
            - sail
        depends_on:
            - laravel.test
    language-server:
        build:
            context: './docker/language-server'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'pgetinker/language-server'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_KEY: '${APP_KEY}'
            LARAVEL_SAIL: 1
        privileged: true
        deploy:
            resources:
                limits:
                    memory: 750m
        mem_swappiness: 0
        oom_kill_disable: false
        volumes:
            - './services/language-server:/var/www/html'
            - './shared/libs:/opt/libs'
            - './shared/emsdk:/opt/emsdk'
        networks:
            - sail
    screenshot:
        build:
            context: './docker/screenshot'
            dockerfile: Dockerfile
        image: 'pgetinker/screenshot'
        networks:
            - sail
    proxy:
        build:
            context: './docker/nginx'
            dockerfile: Dockerfile
        image: pgetinker/proxy
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - sail
        depends_on:
            laravel.test:
                condition: service_healthy
            language-server:
                condition: service_started
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
