.PHONY: all clean olcPixelGameEngine

all: olcPixelGameEngine

olcPixelGameEngine:
	$(MAKE) -C v2.23
	$(MAKE) -C v2.24
	$(MAKE) -C v2.25
	$(MAKE) -C v2.26
	$(MAKE) -C v2.27
	$(MAKE) -C v2.28
	$(MAKE) -C v2.29
	$(MAKE) -C dev

clean:
	$(MAKE) -C v2.23 clean
	$(MAKE) -C v2.24 clean
	$(MAKE) -C v2.25 clean
	$(MAKE) -C v2.26 clean
	$(MAKE) -C v2.27 clean
	$(MAKE) -C v2.28 clean
	$(MAKE) -C v2.29 clean
	$(MAKE) -C dev clean
