name: UnitTests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

jobs:
  pgetinker-tests:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Load Docker Cache
        run: |
          sudo systemctl stop docker.socket
          sudo systemctl stop docker
          sudo cache-load docker-cache /var/lib
          sudo systemctl start docker

      - name: Load Emscripten Cache
        run: cache-load emsdk-cache ./shared

      - name: Initialize PGEtinker
        run: ./scripts/pgetinker initialize ci
      
      - name: Start PGEtinker
        run: ./scripts/pgetinker up -d

      - name: Run Unit Tests
        run: ./scripts/pgetinker test

      - name: Run Browser Tests
        run: ./scripts/pgetinker dusk

      - name: Stop PGEtinker
        run: ./scripts/pgetinker down
      
      - name: Save Emscripten Cache
        run: cache-save ./shared/emsdk emsdk-cache

      - name: Save Docker Cache
        run: |
          sudo systemctl stop docker.socket
          sudo systemctl stop docker
          sudo cache-save /var/lib/docker docker-cache
          sudo systemctl start docker
