name: UnitTests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

jobs:
  pgetinker-tests:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Load Emscripten Cache
        run: (cd shared; tar -xvpf /mnt/docker/emsdk.tar)

      - name: Initialize PGEtinker
        run: ./scripts/pgetinker initialize ci
      
      - name: Start PGEtinker
        run: ./scripts/pgetinker up -d

      - name: Run Unit Tests
        run: ./scripts/pgetinker test

      - name: Run Browser Tests
        run: ./scripts/pgetinker dusk

      - name: Stop PGEtinker
        run: ./scripts/pgetinker down
      
      - name: Save Emscripten Cache
        run: (cd shared; sudo tar -cvpf /mnt/docker/emsdk.tar emsdk/)

