#!/usr/bin/env bash

if [ "$SUPERVISOR_HUGO_USER" != "root" ] && [ "$SUPERVISOR_HUGO_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_HUGO_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_HUGO_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
    exit
else
    echo "$PWD $APP_URL"
    git config --global --add safe.directory /app
    exec hugo --baseURL "$APP_URL/wiki/" -w
fi
